### ISSUE TITLE
[Bug] 500 Server Error when entering protected session

### ISSUE THREAD

**Issue by cculbreath** [zadam/trilium#510]
After updating to 0.31.3, I receive a 500 server error when unlocking protected notes. The behavior is the same on my local MacOS installation (downloaded from release binary) and on my docker-based server install. While I recall receiving a 500-error banner in both the local and remote installation, I can't seem to reproduce the 500-error banner locally now. There is however a 500-error reported in the console log (locally and remote)
```
18:34:51 Response #12: 500
18:34:51 Request #13 to GET notes/undefined/attributes
utils.js:183 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at Object.getMimeTypeClass (utils.js:183)
    at updateNoteView (note_detail.js:163)
    at loadNoteDetail (note_detail.js:204)
server.js:92 18:34:51 Response #13: 500
attributes.js:47 Uncaught (in promise) TypeError: attributes.filter is not a function
    at showAttributes (attributes.js:47)
```

While the tree renders with note names upon entering the protected session, I am unable to view the note contents. There doesn't seem to be a problem if I un-protect the note; I can view it. 

Here is the related entry in the trilium log:
```
18:26:17.325 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error: Cannot decrypt content for noteId=Z21HGziL0HDZ: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
    at Decipheriv.final (internal/crypto/cipher.js:172:28)
    at Object.decrypt (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/data_encryption.js:66:87)
    at Object.decryptNoteContent (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/protected_session.js:62:50)
    at Note.getContent (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/entities/note.js:91:45)
Outside stack: Error
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:187:23)
    at cls.init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:80:38)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:5:28)
    at router.(anonymous function) (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:75:38)
    at Layer.handle [as handle_request] (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at csrf (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/csurf/index.js:117:5) 
18:26:17.327 INFO  ERROR: get /api/notes/:noteId threw exception: Error: Cannot decrypt content for noteId=Z21HGziL0HDZ: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
    at Decipheriv.final (internal/crypto/cipher.js:172:28)
    at Object.decrypt (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/data_encryption.js:66:87)
    at Object.decryptNoteContent (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/protected_session.js:62:50)
    at Note.getContent (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/entities/note.js:91:45) 
```

**Comment by zadam** [comment]
Hello, thank you for reporting this. I have a hypothesis that this could be caused by the fact that the note content has not been encrypted at all and that's why the attempt to decrypt (unencrypted) content failed. I tried to reproduce it locally and it is consistent with what you experienced.

You previously used 0.30.X version, is that correct? One of the versions had a bug which encrypted only title and not the content. As part of migration to 0.30.7 (or 0.31.X), this should have been fixed with a special migration script, but it looks like this didn't help fully.

However now, unprotecting the note should fix the problem (for that particular note). Could you now try to protect this note again - I believe it should now work correctly.

**Comment by cculbreath** [comment]
I can't view protected notes in any capacity. If I create a new note, protect it, and then enter a protected session, the title is correctly decrypted, but the detail-view fails to load for the note. Only if I unprotect the note, can it can be viewed again.

**Comment by zadam** [comment]
Could you do a little experiment? Open a protected note which gives you trouble (can be outside of protected session), go to note actions => note info, and copy noteId to clipboard.

Then go to Menu -> Open SQL Console and execute this query:

```
select * from note_contents where noteId = '[noteId from clipboard]'
```

Now in the result, column content, do you see plain text of your note or is it just garbled (encrypted) string?

**Comment by cculbreath** [comment]
```sql
select * from note_contents where noteID='ZWgzaMUireQZ'
```
<table>
<tr><th>content</th><th>hash</th><th>noteId</th><th>utcDateModified</th>
</tr>
<tr>
<td>Test Protected Note contents</td><td>VRp/3ril+R6iK7vxS1LmU8ms+Mc=</td><td> ZWgzaMUireQZ</td><td>2019-05-04 10:07:15.265Z</td</tr>
</table>

**Comment by cculbreath** [comment]
javascript console log when attempting to view note detail below (note title in tree is successfully decrypted)
```log
03:17:00 Request #19 to GET notes/ZWgzaMUireQZ
server.js:92 03:17:00 Response #19: 500
server.js:48 03:17:00 Request #20 to GET notes/undefined/attributes
utils.js:183 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at Object.getMimeTypeClass (utils.js:183)
    at updateNoteView (note_detail.js:163)
    at loadNoteDetail (note_detail.js:204)
server.js:92 03:17:00 Response #20: 500
attributes.js:47 Uncaught (in promise) TypeError: attributes.filter is not a function
    at showAttributes (attributes.js:47)
server.js:48 03:17:02 Request #21 to GET notes/9iAHBimOxWzM
```

**Comment by zadam** [comment]
I managed to reproduce and fix the issue. At first I didn't realize you used context menu to protect/unprotect the notes (I usually use buttons) - the difference which should not matter, but ultimately it did (because the context menu one is a mass action and has bit different implementation).

I appreciate your help in finding and analyzing the issue! I will release fixed version soon.

**Comment by cculbreath** [comment]
Nice catch on the context-menu activation 👍

I hadn't considered the possibility that this could be a quirk related to interaction habits.
