### ISSUE TITLE
(Bug report) note.deleteNote() is broken after an update

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#2900]
### Trilium Version

0.52.1-beta

### What operating system are you using?

Windows

### What is your setup?

Server access only

### Operating System Version

Windows 10 version 2004

### Description

`note.deleteNote()` was introduced in #2792 and it is operational till the version 0.51.2.

However, it is broken in 0.52.1-beta. Trying to invoke it will cause the following error message:

```
ERROR: Execution of script "xxx" (xxx) failed with error: Load of script note "xxx" (xxx) failed with: handlers.runAttachedRelations is not a function
```
