### ISSUE TITLE
(Bug report) Edited Notes tab is not working in 0.60.0

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#3968]
### Trilium Version

0.60.0-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Manjaro

### Description

In journal notes, clicking on `Edited Notes` tab will show an error.
```
note.getBestNotePath is not a function
```

### Error logs

```
ERROR: get /api/edited-notes/:date threw exception: 'note.getBestNotePath is not a function', stack: TypeError: note.getBestNotePath is not a function
    at getNotePathData (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/routes/api/note_revisions.js:147:26)
    at getEditedNotesOnDate (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/routes/api/note_revisions.js:138:50)
    at Function.cb (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/routes/routes.js:411:34)
    at Function.sqliteTransaction (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/services/sql.js:242:52)
    at /home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/routes/routes.js:413:44
    at /home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/home/nate/soft/trilium/trilium-trans/trilium-linux-x64/resources/app.asar/src/services/cls.js:5:22)
JS Error: 500 GET /api/edited-notes/2023-05-24 - note.getBestNotePath is not a function
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/assets/v0.60.0-beta/app-dist/desktop.js:2:103549)
    at Object.throwError (http://127.0.0.1:37840/assets/v0.60.0-beta/app-dist/desktop.js:2:88827)
    at h (http://127.0.0.1:37840/assets/v0.60.0-beta/app-dist/desktop.js:2:84767)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/assets/v0.60.0-beta/app-dist/desktop.js:2:85648)
```
